name: Create Patch Release

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'write'

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - name: Bump version
        run: |
          git config --global user.email khanhmenly123@gmail.com
          git config --global user.name vkng1104
          ./tools/create_release.sh major
